from app.utils.normalization import (
    normalize_username,
    normalize_display_name,
    normalize_url,
    normalize_domain,
    normalize_bio,
    normalize_keywords,
    normalize_aliases,
    extract_domain_from_url,
    extract_domains_from_urls,
    extract_email_domain,
    normalize_phone,
    NormalizedCandidate,
)

from app.utils.similarity import (
    levenshtein_similarity,
    jaro_winkler_similarity,
    token_set_similarity,
    token_sort_similarity,
    partial_ratio_similarity,
    calculate_name_similarity,
    detect_lookalike_pattern,
    calculate_best_similarity,
)

from app.utils.image_similarity import (
    download_image,
    compute_phash,
    compute_dhash,
    compute_average_hash,
    hamming_distance,
    phash_similarity,
    compare_images,
    compare_logo_with_official,
)

from app.utils.risk_scoring import (
    RiskWeights,
    DEFAULT_WEIGHTS,
    calculate_risk_score,
    determine_risk_level,
    determine_classification,
    calculate_confidence,
    generate_reasons,
    assess_false_positive_risk,
    RiskLevel,
    ThreatClassification,
)

__all__ = [
    "normalize_username",
    "normalize_display_name",
    "normalize_url",
    "normalize_domain",
    "normalize_bio",
    "normalize_keywords",
    "normalize_aliases",
    "extract_domain_from_url",
    "extract_domains_from_urls",
    "extract_email_domain",
    "normalize_phone",
    "NormalizedCandidate",
    "levenshtein_similarity",
    "jaro_winkler_similarity",
    "token_set_similarity",
    "token_sort_similarity",
    "partial_ratio_similarity",
    "calculate_name_similarity",
    "detect_lookalike_pattern",
    "calculate_best_similarity",
    "download_image",
    "compute_phash",
    "compute_dhash",
    "compute_average_hash",
    "hamming_distance",
    "phash_similarity",
    "compare_images",
    "compare_logo_with_official",
    "RiskWeights",
    "DEFAULT_WEIGHTS",
    "calculate_risk_score",
    "determine_risk_level",
    "determine_classification",
    "calculate_confidence",
    "generate_reasons",
    "assess_false_positive_risk",
    "RiskLevel",
    "ThreatClassification",
]